### ISSUE TITLE
Logout action

### ISSUE THREAD

**Issue by AtulDwivedi** [AtulDwivedi/ors#10]
# Description
Logut is very critical for any applicatioin in order to secure the application from unautorised access.
# Task list
- [ ] Remove session attribute(s)
- [ ] Invalidate the session
- [ ] Navigate user back to guest home page
----
[_help_](http://www.javaworld.com/article/2072937/java-web-development/solving-the-logout-problem-properly-and-elegantly.html)
