### ISSUE TITLE
Login action

### ISSUE THREAD

**Issue by AtulDwivedi** [AtulDwivedi/ors#12]
# Task list

- [ ] Retrieve user credentials from form submission
- [ ] Retrieve user credentials from back-end system
- [ ] Check the validity of the user by checking form data against back-end data
- [ ] If user is valid, put `userName` as session attribute and navigate user to home page
- [ ] Else navigate user back to login page with proper error message
- [ ] **Test the enhancement**
## References
* [Help](http://www.javaworld.com/article/2072937/java-web-development/solving-the-logout-problem-properly-and-elegantly.html)
